
server:
  port: 8888

github:
  clientId: cb5cb708ae9786053626
  clientSecret: 8deb4e3ec8daada6b9619de652e8494fc3019e84
  redirectUri: http://127.0.0.1:8888/callback

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/depot
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: life.male.community.pojo

logging:
  config: classpath:logback-spring.xml


log:
 maxvalue: 2
 file: logs/zhangjiale.log






